version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "go-allowance"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ff9eio9h3ku8"
s3_prefix = "go-allowance"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
